workflows:
  unity-ios-workflow:
    name: Build Unity iOS App
    environment:
      vars:
        UNITY_VERSION: 2022.3.0f1
      xcode: latest
    scripts:
      - name: Install Unity
        script: |
          curl -o unityhub.AppImage -L "https://public-cdn.cloud.unity3d.com/hub/prod/UnityHub.AppImage"
          chmod +x unityhub.AppImage
      - name: Build iOS
        script: |
          # Giả sử bạn có file build script trong Unity
          /Applications/Unity/Hub/Editor/$UNITY_VERSION/Unity.app/Contents/MacOS/Unity \
            -batchmode -nographics -quit -projectPath . -executeMethod BuildScript.PerformIOSBuild
    artifacts:
      - build/ios/*.ipa
