workflows:
  build_ios_app:
    name: Build Unity iOS App
    environment:
      unity: 2021.3.3f1 # <-- đổi về version có sẵn
      xcode: latest
    scripts:
      - name: Build iOS
        script: |
          /Applications/Unity/Hub/Editor/2021.3.3f1/Unity.app/Contents/MacOS/Unity \
            -batchmode \
            -nographics \
            -quit \
            -projectPath . \
            -executeMethod BuildScript.PerformIOSBuild
    artifacts:
      - build/ios/**/*
